// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Borealis.Communication.Messages
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public enum LedstripStatus : byte
{
  IDLE = 0,
  DISPALYING_FRAME = 1,
  PAUSED = 2,
  PLAYING = 3,
};

public enum LedstripChip : byte
{
  DEFAULT = 0,
  WS2812B = 1,
  WS2813 = 2,
  WS2815 = 3,
  APA102 = 4,
  SK6812 = 5,
  SK9822 = 6,
};

public enum ErrorIds : short
{
  UNKNOWNERROR = 0,
  INTERNALERROR = 500,
  CONFIGURATIONERROR = 600,
};

public struct LedstripStatusMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static LedstripStatusMessage GetRootAsLedstripStatusMessage(ByteBuffer _bb) { return GetRootAsLedstripStatusMessage(_bb, new LedstripStatusMessage()); }
  public static LedstripStatusMessage GetRootAsLedstripStatusMessage(ByteBuffer _bb, LedstripStatusMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LedstripStatusMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string LedstripId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLedstripIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetLedstripIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetLedstripIdArray() { return __p.__vector_as_array<byte>(4); }
  public Borealis.Communication.Messages.LedstripStatus LedstripStatus { get { int o = __p.__offset(6); return o != 0 ? (Borealis.Communication.Messages.LedstripStatus)__p.bb.Get(o + __p.bb_pos) : Borealis.Communication.Messages.LedstripStatus.IDLE; } }

  public static Offset<Borealis.Communication.Messages.LedstripStatusMessage> CreateLedstripStatusMessage(FlatBufferBuilder builder,
      StringOffset ledstrip_idOffset = default(StringOffset),
      Borealis.Communication.Messages.LedstripStatus ledstrip_status = Borealis.Communication.Messages.LedstripStatus.IDLE) {
    builder.StartTable(2);
    LedstripStatusMessage.AddLedstripId(builder, ledstrip_idOffset);
    LedstripStatusMessage.AddLedstripStatus(builder, ledstrip_status);
    return LedstripStatusMessage.EndLedstripStatusMessage(builder);
  }

  public static void StartLedstripStatusMessage(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddLedstripId(FlatBufferBuilder builder, StringOffset ledstripIdOffset) { builder.AddOffset(0, ledstripIdOffset.Value, 0); }
  public static void AddLedstripStatus(FlatBufferBuilder builder, Borealis.Communication.Messages.LedstripStatus ledstripStatus) { builder.AddByte(1, (byte)ledstripStatus, 0); }
  public static Offset<Borealis.Communication.Messages.LedstripStatusMessage> EndLedstripStatusMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.LedstripStatusMessage>(o);
  }
  public LedstripStatusMessageT UnPack() {
    var _o = new LedstripStatusMessageT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(LedstripStatusMessageT _o) {
    _o.LedstripId = this.LedstripId;
    _o.LedstripStatus = this.LedstripStatus;
  }
  public static Offset<Borealis.Communication.Messages.LedstripStatusMessage> Pack(FlatBufferBuilder builder, LedstripStatusMessageT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.LedstripStatusMessage>);
    var _ledstrip_id = _o.LedstripId == null ? default(StringOffset) : builder.CreateString(_o.LedstripId);
    return CreateLedstripStatusMessage(
      builder,
      _ledstrip_id,
      _o.LedstripStatus);
  }
}

public class LedstripStatusMessageT
{
  public string LedstripId { get; set; }
  public Borealis.Communication.Messages.LedstripStatus LedstripStatus { get; set; }

  public LedstripStatusMessageT() {
    this.LedstripId = null;
    this.LedstripStatus = Borealis.Communication.Messages.LedstripStatus.IDLE;
  }
}

public struct ConfigurationMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static ConfigurationMessage GetRootAsConfigurationMessage(ByteBuffer _bb) { return GetRootAsConfigurationMessage(_bb, new ConfigurationMessage()); }
  public static ConfigurationMessage GetRootAsConfigurationMessage(ByteBuffer _bb, ConfigurationMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ConfigurationMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Borealis.Communication.Messages.LedstripMessage? Ledstrips(int j) { int o = __p.__offset(4); return o != 0 ? (Borealis.Communication.Messages.LedstripMessage?)(new Borealis.Communication.Messages.LedstripMessage()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int LedstripsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Borealis.Communication.Messages.ConfigurationMessage> CreateConfigurationMessage(FlatBufferBuilder builder,
      VectorOffset ledstripsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ConfigurationMessage.AddLedstrips(builder, ledstripsOffset);
    return ConfigurationMessage.EndConfigurationMessage(builder);
  }

  public static void StartConfigurationMessage(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddLedstrips(FlatBufferBuilder builder, VectorOffset ledstripsOffset) { builder.AddOffset(0, ledstripsOffset.Value, 0); }
  public static VectorOffset CreateLedstripsVector(FlatBufferBuilder builder, Offset<Borealis.Communication.Messages.LedstripMessage>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateLedstripsVectorBlock(FlatBufferBuilder builder, Offset<Borealis.Communication.Messages.LedstripMessage>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLedstripsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Borealis.Communication.Messages.LedstripMessage>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLedstripsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Borealis.Communication.Messages.LedstripMessage>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartLedstripsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Borealis.Communication.Messages.ConfigurationMessage> EndConfigurationMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.ConfigurationMessage>(o);
  }
  public ConfigurationMessageT UnPack() {
    var _o = new ConfigurationMessageT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ConfigurationMessageT _o) {
    _o.Ledstrips = new List<Borealis.Communication.Messages.LedstripMessageT>();
    for (var _j = 0; _j < this.LedstripsLength; ++_j) {_o.Ledstrips.Add(this.Ledstrips(_j).HasValue ? this.Ledstrips(_j).Value.UnPack() : null);}
  }
  public static Offset<Borealis.Communication.Messages.ConfigurationMessage> Pack(FlatBufferBuilder builder, ConfigurationMessageT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.ConfigurationMessage>);
    var _ledstrips = default(VectorOffset);
    if (_o.Ledstrips != null) {
      var __ledstrips = new Offset<Borealis.Communication.Messages.LedstripMessage>[_o.Ledstrips.Count];
      for (var _j = 0; _j < __ledstrips.Length; ++_j) { __ledstrips[_j] = Borealis.Communication.Messages.LedstripMessage.Pack(builder, _o.Ledstrips[_j]); }
      _ledstrips = CreateLedstripsVector(builder, __ledstrips);
    }
    return CreateConfigurationMessage(
      builder,
      _ledstrips);
  }
}

public class ConfigurationMessageT
{
  public List<Borealis.Communication.Messages.LedstripMessageT> Ledstrips { get; set; }

  public ConfigurationMessageT() {
    this.Ledstrips = null;
  }
}

public struct LedstripMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static LedstripMessage GetRootAsLedstripMessage(ByteBuffer _bb) { return GetRootAsLedstripMessage(_bb, new LedstripMessage()); }
  public static LedstripMessage GetRootAsLedstripMessage(ByteBuffer _bb, LedstripMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LedstripMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte BusId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public string LedstripId { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLedstripIdBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetLedstripIdBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetLedstripIdArray() { return __p.__vector_as_array<byte>(6); }
  public ushort PixelCount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public Borealis.Communication.Messages.LedstripChip Chip { get { int o = __p.__offset(10); return o != 0 ? (Borealis.Communication.Messages.LedstripChip)__p.bb.Get(o + __p.bb_pos) : Borealis.Communication.Messages.LedstripChip.DEFAULT; } }

  public static Offset<Borealis.Communication.Messages.LedstripMessage> CreateLedstripMessage(FlatBufferBuilder builder,
      byte bus_id = 0,
      StringOffset ledstrip_idOffset = default(StringOffset),
      ushort pixel_count = 0,
      Borealis.Communication.Messages.LedstripChip chip = Borealis.Communication.Messages.LedstripChip.DEFAULT) {
    builder.StartTable(4);
    LedstripMessage.AddLedstripId(builder, ledstrip_idOffset);
    LedstripMessage.AddPixelCount(builder, pixel_count);
    LedstripMessage.AddChip(builder, chip);
    LedstripMessage.AddBusId(builder, bus_id);
    return LedstripMessage.EndLedstripMessage(builder);
  }

  public static void StartLedstripMessage(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddBusId(FlatBufferBuilder builder, byte busId) { builder.AddByte(0, busId, 0); }
  public static void AddLedstripId(FlatBufferBuilder builder, StringOffset ledstripIdOffset) { builder.AddOffset(1, ledstripIdOffset.Value, 0); }
  public static void AddPixelCount(FlatBufferBuilder builder, ushort pixelCount) { builder.AddUshort(2, pixelCount, 0); }
  public static void AddChip(FlatBufferBuilder builder, Borealis.Communication.Messages.LedstripChip chip) { builder.AddByte(3, (byte)chip, 0); }
  public static Offset<Borealis.Communication.Messages.LedstripMessage> EndLedstripMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.LedstripMessage>(o);
  }
  public LedstripMessageT UnPack() {
    var _o = new LedstripMessageT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(LedstripMessageT _o) {
    _o.BusId = this.BusId;
    _o.LedstripId = this.LedstripId;
    _o.PixelCount = this.PixelCount;
    _o.Chip = this.Chip;
  }
  public static Offset<Borealis.Communication.Messages.LedstripMessage> Pack(FlatBufferBuilder builder, LedstripMessageT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.LedstripMessage>);
    var _ledstrip_id = _o.LedstripId == null ? default(StringOffset) : builder.CreateString(_o.LedstripId);
    return CreateLedstripMessage(
      builder,
      _o.BusId,
      _ledstrip_id,
      _o.PixelCount,
      _o.Chip);
  }
}

public class LedstripMessageT
{
  public byte BusId { get; set; }
  public string LedstripId { get; set; }
  public ushort PixelCount { get; set; }
  public Borealis.Communication.Messages.LedstripChip Chip { get; set; }

  public LedstripMessageT() {
    this.BusId = 0;
    this.LedstripId = null;
    this.PixelCount = 0;
    this.Chip = Borealis.Communication.Messages.LedstripChip.DEFAULT;
  }
}

public struct FrameMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static FrameMessage GetRootAsFrameMessage(ByteBuffer _bb) { return GetRootAsFrameMessage(_bb, new FrameMessage()); }
  public static FrameMessage GetRootAsFrameMessage(ByteBuffer _bb, FrameMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FrameMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Borealis.Communication.Messages.PixelMessage? Pixels(int j) { int o = __p.__offset(4); return o != 0 ? (Borealis.Communication.Messages.PixelMessage?)(new Borealis.Communication.Messages.PixelMessage()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int PixelsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Borealis.Communication.Messages.FrameMessage> CreateFrameMessage(FlatBufferBuilder builder,
      VectorOffset pixelsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    FrameMessage.AddPixels(builder, pixelsOffset);
    return FrameMessage.EndFrameMessage(builder);
  }

  public static void StartFrameMessage(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPixels(FlatBufferBuilder builder, VectorOffset pixelsOffset) { builder.AddOffset(0, pixelsOffset.Value, 0); }
  public static VectorOffset CreatePixelsVector(FlatBufferBuilder builder, Offset<Borealis.Communication.Messages.PixelMessage>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreatePixelsVectorBlock(FlatBufferBuilder builder, Offset<Borealis.Communication.Messages.PixelMessage>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePixelsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Borealis.Communication.Messages.PixelMessage>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePixelsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Borealis.Communication.Messages.PixelMessage>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPixelsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Borealis.Communication.Messages.FrameMessage> EndFrameMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.FrameMessage>(o);
  }
  public FrameMessageT UnPack() {
    var _o = new FrameMessageT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FrameMessageT _o) {
    _o.Pixels = new List<Borealis.Communication.Messages.PixelMessageT>();
    for (var _j = 0; _j < this.PixelsLength; ++_j) {_o.Pixels.Add(this.Pixels(_j).HasValue ? this.Pixels(_j).Value.UnPack() : null);}
  }
  public static Offset<Borealis.Communication.Messages.FrameMessage> Pack(FlatBufferBuilder builder, FrameMessageT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.FrameMessage>);
    var _pixels = default(VectorOffset);
    if (_o.Pixels != null) {
      var __pixels = new Offset<Borealis.Communication.Messages.PixelMessage>[_o.Pixels.Count];
      for (var _j = 0; _j < __pixels.Length; ++_j) { __pixels[_j] = Borealis.Communication.Messages.PixelMessage.Pack(builder, _o.Pixels[_j]); }
      _pixels = CreatePixelsVector(builder, __pixels);
    }
    return CreateFrameMessage(
      builder,
      _pixels);
  }
}

public class FrameMessageT
{
  public List<Borealis.Communication.Messages.PixelMessageT> Pixels { get; set; }

  public FrameMessageT() {
    this.Pixels = null;
  }
}

public struct PixelMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PixelMessage GetRootAsPixelMessage(ByteBuffer _bb) { return GetRootAsPixelMessage(_bb, new PixelMessage()); }
  public static PixelMessage GetRootAsPixelMessage(ByteBuffer _bb, PixelMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PixelMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte R { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public byte G { get { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public byte B { get { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public byte W { get { int o = __p.__offset(10); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<Borealis.Communication.Messages.PixelMessage> CreatePixelMessage(FlatBufferBuilder builder,
      byte r = 0,
      byte g = 0,
      byte b = 0,
      byte w = 0) {
    builder.StartTable(4);
    PixelMessage.AddW(builder, w);
    PixelMessage.AddB(builder, b);
    PixelMessage.AddG(builder, g);
    PixelMessage.AddR(builder, r);
    return PixelMessage.EndPixelMessage(builder);
  }

  public static void StartPixelMessage(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddR(FlatBufferBuilder builder, byte r) { builder.AddByte(0, r, 0); }
  public static void AddG(FlatBufferBuilder builder, byte g) { builder.AddByte(1, g, 0); }
  public static void AddB(FlatBufferBuilder builder, byte b) { builder.AddByte(2, b, 0); }
  public static void AddW(FlatBufferBuilder builder, byte w) { builder.AddByte(3, w, 0); }
  public static Offset<Borealis.Communication.Messages.PixelMessage> EndPixelMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.PixelMessage>(o);
  }
  public PixelMessageT UnPack() {
    var _o = new PixelMessageT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(PixelMessageT _o) {
    _o.R = this.R;
    _o.G = this.G;
    _o.B = this.B;
    _o.W = this.W;
  }
  public static Offset<Borealis.Communication.Messages.PixelMessage> Pack(FlatBufferBuilder builder, PixelMessageT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.PixelMessage>);
    return CreatePixelMessage(
      builder,
      _o.R,
      _o.G,
      _o.B,
      _o.W);
  }
}

public class PixelMessageT
{
  public byte R { get; set; }
  public byte G { get; set; }
  public byte B { get; set; }
  public byte W { get; set; }

  public PixelMessageT() {
    this.R = 0;
    this.G = 0;
    this.B = 0;
    this.W = 0;
  }
}

public struct ConnectRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static ConnectRequest GetRootAsConnectRequest(ByteBuffer _bb) { return GetRootAsConnectRequest(_bb, new ConnectRequest()); }
  public static ConnectRequest GetRootAsConnectRequest(ByteBuffer _bb, ConnectRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ConnectRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ConfigurationConcurrencyToken { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetConfigurationConcurrencyTokenBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetConfigurationConcurrencyTokenBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetConfigurationConcurrencyTokenArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Borealis.Communication.Messages.ConnectRequest> CreateConnectRequest(FlatBufferBuilder builder,
      StringOffset configuration_concurrency_tokenOffset = default(StringOffset)) {
    builder.StartTable(1);
    ConnectRequest.AddConfigurationConcurrencyToken(builder, configuration_concurrency_tokenOffset);
    return ConnectRequest.EndConnectRequest(builder);
  }

  public static void StartConnectRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddConfigurationConcurrencyToken(FlatBufferBuilder builder, StringOffset configurationConcurrencyTokenOffset) { builder.AddOffset(0, configurationConcurrencyTokenOffset.Value, 0); }
  public static Offset<Borealis.Communication.Messages.ConnectRequest> EndConnectRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.ConnectRequest>(o);
  }
  public ConnectRequestT UnPack() {
    var _o = new ConnectRequestT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ConnectRequestT _o) {
    _o.ConfigurationConcurrencyToken = this.ConfigurationConcurrencyToken;
  }
  public static Offset<Borealis.Communication.Messages.ConnectRequest> Pack(FlatBufferBuilder builder, ConnectRequestT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.ConnectRequest>);
    var _configuration_concurrency_token = _o.ConfigurationConcurrencyToken == null ? default(StringOffset) : builder.CreateString(_o.ConfigurationConcurrencyToken);
    return CreateConnectRequest(
      builder,
      _configuration_concurrency_token);
  }
}

public class ConnectRequestT
{
  public string ConfigurationConcurrencyToken { get; set; }

  public ConnectRequestT() {
    this.ConfigurationConcurrencyToken = null;
  }
}

public struct ConnectReply : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static ConnectReply GetRootAsConnectReply(ByteBuffer _bb) { return GetRootAsConnectReply(_bb, new ConnectReply()); }
  public static ConnectReply GetRootAsConnectReply(ByteBuffer _bb, ConnectReply obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ConnectReply __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool ConfigurationConcurrencyTokenValid { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Borealis.Communication.Messages.ConnectReply> CreateConnectReply(FlatBufferBuilder builder,
      bool configuration_concurrency_token_valid = false) {
    builder.StartTable(1);
    ConnectReply.AddConfigurationConcurrencyTokenValid(builder, configuration_concurrency_token_valid);
    return ConnectReply.EndConnectReply(builder);
  }

  public static void StartConnectReply(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddConfigurationConcurrencyTokenValid(FlatBufferBuilder builder, bool configurationConcurrencyTokenValid) { builder.AddBool(0, configurationConcurrencyTokenValid, false); }
  public static Offset<Borealis.Communication.Messages.ConnectReply> EndConnectReply(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.ConnectReply>(o);
  }
  public ConnectReplyT UnPack() {
    var _o = new ConnectReplyT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ConnectReplyT _o) {
    _o.ConfigurationConcurrencyTokenValid = this.ConfigurationConcurrencyTokenValid;
  }
  public static Offset<Borealis.Communication.Messages.ConnectReply> Pack(FlatBufferBuilder builder, ConnectReplyT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.ConnectReply>);
    return CreateConnectReply(
      builder,
      _o.ConfigurationConcurrencyTokenValid);
  }
}

public class ConnectReplyT
{
  public bool ConfigurationConcurrencyTokenValid { get; set; }

  public ConnectReplyT() {
    this.ConfigurationConcurrencyTokenValid = false;
  }
}

public struct SetConfigurationRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static SetConfigurationRequest GetRootAsSetConfigurationRequest(ByteBuffer _bb) { return GetRootAsSetConfigurationRequest(_bb, new SetConfigurationRequest()); }
  public static SetConfigurationRequest GetRootAsSetConfigurationRequest(ByteBuffer _bb, SetConfigurationRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetConfigurationRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string ConcurrencyToken { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetConcurrencyTokenBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetConcurrencyTokenBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetConcurrencyTokenArray() { return __p.__vector_as_array<byte>(4); }
  public Borealis.Communication.Messages.ConfigurationMessage? Configuration { get { int o = __p.__offset(6); return o != 0 ? (Borealis.Communication.Messages.ConfigurationMessage?)(new Borealis.Communication.Messages.ConfigurationMessage()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Borealis.Communication.Messages.SetConfigurationRequest> CreateSetConfigurationRequest(FlatBufferBuilder builder,
      StringOffset concurrency_tokenOffset = default(StringOffset),
      Offset<Borealis.Communication.Messages.ConfigurationMessage> configurationOffset = default(Offset<Borealis.Communication.Messages.ConfigurationMessage>)) {
    builder.StartTable(2);
    SetConfigurationRequest.AddConfiguration(builder, configurationOffset);
    SetConfigurationRequest.AddConcurrencyToken(builder, concurrency_tokenOffset);
    return SetConfigurationRequest.EndSetConfigurationRequest(builder);
  }

  public static void StartSetConfigurationRequest(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddConcurrencyToken(FlatBufferBuilder builder, StringOffset concurrencyTokenOffset) { builder.AddOffset(0, concurrencyTokenOffset.Value, 0); }
  public static void AddConfiguration(FlatBufferBuilder builder, Offset<Borealis.Communication.Messages.ConfigurationMessage> configurationOffset) { builder.AddOffset(1, configurationOffset.Value, 0); }
  public static Offset<Borealis.Communication.Messages.SetConfigurationRequest> EndSetConfigurationRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.SetConfigurationRequest>(o);
  }
  public SetConfigurationRequestT UnPack() {
    var _o = new SetConfigurationRequestT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SetConfigurationRequestT _o) {
    _o.ConcurrencyToken = this.ConcurrencyToken;
    _o.Configuration = this.Configuration.HasValue ? this.Configuration.Value.UnPack() : null;
  }
  public static Offset<Borealis.Communication.Messages.SetConfigurationRequest> Pack(FlatBufferBuilder builder, SetConfigurationRequestT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.SetConfigurationRequest>);
    var _concurrency_token = _o.ConcurrencyToken == null ? default(StringOffset) : builder.CreateString(_o.ConcurrencyToken);
    var _configuration = _o.Configuration == null ? default(Offset<Borealis.Communication.Messages.ConfigurationMessage>) : Borealis.Communication.Messages.ConfigurationMessage.Pack(builder, _o.Configuration);
    return CreateSetConfigurationRequest(
      builder,
      _concurrency_token,
      _configuration);
  }
}

public class SetConfigurationRequestT
{
  public string ConcurrencyToken { get; set; }
  public Borealis.Communication.Messages.ConfigurationMessageT Configuration { get; set; }

  public SetConfigurationRequestT() {
    this.ConcurrencyToken = null;
    this.Configuration = null;
  }
}

public struct SetConfigurationReply : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static SetConfigurationReply GetRootAsSetConfigurationReply(ByteBuffer _bb) { return GetRootAsSetConfigurationReply(_bb, new SetConfigurationReply()); }
  public static SetConfigurationReply GetRootAsSetConfigurationReply(ByteBuffer _bb, SetConfigurationReply obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetConfigurationReply __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Success { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string ErrorMessage { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetErrorMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetErrorMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetErrorMessageArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<Borealis.Communication.Messages.SetConfigurationReply> CreateSetConfigurationReply(FlatBufferBuilder builder,
      bool success = false,
      StringOffset error_messageOffset = default(StringOffset)) {
    builder.StartTable(2);
    SetConfigurationReply.AddErrorMessage(builder, error_messageOffset);
    SetConfigurationReply.AddSuccess(builder, success);
    return SetConfigurationReply.EndSetConfigurationReply(builder);
  }

  public static void StartSetConfigurationReply(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddSuccess(FlatBufferBuilder builder, bool success) { builder.AddBool(0, success, false); }
  public static void AddErrorMessage(FlatBufferBuilder builder, StringOffset errorMessageOffset) { builder.AddOffset(1, errorMessageOffset.Value, 0); }
  public static Offset<Borealis.Communication.Messages.SetConfigurationReply> EndSetConfigurationReply(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.SetConfigurationReply>(o);
  }
  public SetConfigurationReplyT UnPack() {
    var _o = new SetConfigurationReplyT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SetConfigurationReplyT _o) {
    _o.Success = this.Success;
    _o.ErrorMessage = this.ErrorMessage;
  }
  public static Offset<Borealis.Communication.Messages.SetConfigurationReply> Pack(FlatBufferBuilder builder, SetConfigurationReplyT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.SetConfigurationReply>);
    var _error_message = _o.ErrorMessage == null ? default(StringOffset) : builder.CreateString(_o.ErrorMessage);
    return CreateSetConfigurationReply(
      builder,
      _o.Success,
      _error_message);
  }
}

public class SetConfigurationReplyT
{
  public bool Success { get; set; }
  public string ErrorMessage { get; set; }

  public SetConfigurationReplyT() {
    this.Success = false;
    this.ErrorMessage = null;
  }
}

public struct StartAnimationRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static StartAnimationRequest GetRootAsStartAnimationRequest(ByteBuffer _bb) { return GetRootAsStartAnimationRequest(_bb, new StartAnimationRequest()); }
  public static StartAnimationRequest GetRootAsStartAnimationRequest(ByteBuffer _bb, StartAnimationRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StartAnimationRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string LedstripId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLedstripIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetLedstripIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetLedstripIdArray() { return __p.__vector_as_array<byte>(4); }
  public float Frequency { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public Borealis.Communication.Messages.FrameMessage? InitialFrameBuffer(int j) { int o = __p.__offset(8); return o != 0 ? (Borealis.Communication.Messages.FrameMessage?)(new Borealis.Communication.Messages.FrameMessage()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int InitialFrameBufferLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Borealis.Communication.Messages.StartAnimationRequest> CreateStartAnimationRequest(FlatBufferBuilder builder,
      StringOffset ledstrip_idOffset = default(StringOffset),
      float frequency = 0.0f,
      VectorOffset initial_frame_bufferOffset = default(VectorOffset)) {
    builder.StartTable(3);
    StartAnimationRequest.AddInitialFrameBuffer(builder, initial_frame_bufferOffset);
    StartAnimationRequest.AddFrequency(builder, frequency);
    StartAnimationRequest.AddLedstripId(builder, ledstrip_idOffset);
    return StartAnimationRequest.EndStartAnimationRequest(builder);
  }

  public static void StartStartAnimationRequest(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddLedstripId(FlatBufferBuilder builder, StringOffset ledstripIdOffset) { builder.AddOffset(0, ledstripIdOffset.Value, 0); }
  public static void AddFrequency(FlatBufferBuilder builder, float frequency) { builder.AddFloat(1, frequency, 0.0f); }
  public static void AddInitialFrameBuffer(FlatBufferBuilder builder, VectorOffset initialFrameBufferOffset) { builder.AddOffset(2, initialFrameBufferOffset.Value, 0); }
  public static VectorOffset CreateInitialFrameBufferVector(FlatBufferBuilder builder, Offset<Borealis.Communication.Messages.FrameMessage>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateInitialFrameBufferVectorBlock(FlatBufferBuilder builder, Offset<Borealis.Communication.Messages.FrameMessage>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInitialFrameBufferVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Borealis.Communication.Messages.FrameMessage>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInitialFrameBufferVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Borealis.Communication.Messages.FrameMessage>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInitialFrameBufferVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Borealis.Communication.Messages.StartAnimationRequest> EndStartAnimationRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.StartAnimationRequest>(o);
  }
  public StartAnimationRequestT UnPack() {
    var _o = new StartAnimationRequestT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(StartAnimationRequestT _o) {
    _o.LedstripId = this.LedstripId;
    _o.Frequency = this.Frequency;
    _o.InitialFrameBuffer = new List<Borealis.Communication.Messages.FrameMessageT>();
    for (var _j = 0; _j < this.InitialFrameBufferLength; ++_j) {_o.InitialFrameBuffer.Add(this.InitialFrameBuffer(_j).HasValue ? this.InitialFrameBuffer(_j).Value.UnPack() : null);}
  }
  public static Offset<Borealis.Communication.Messages.StartAnimationRequest> Pack(FlatBufferBuilder builder, StartAnimationRequestT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.StartAnimationRequest>);
    var _ledstrip_id = _o.LedstripId == null ? default(StringOffset) : builder.CreateString(_o.LedstripId);
    var _initial_frame_buffer = default(VectorOffset);
    if (_o.InitialFrameBuffer != null) {
      var __initial_frame_buffer = new Offset<Borealis.Communication.Messages.FrameMessage>[_o.InitialFrameBuffer.Count];
      for (var _j = 0; _j < __initial_frame_buffer.Length; ++_j) { __initial_frame_buffer[_j] = Borealis.Communication.Messages.FrameMessage.Pack(builder, _o.InitialFrameBuffer[_j]); }
      _initial_frame_buffer = CreateInitialFrameBufferVector(builder, __initial_frame_buffer);
    }
    return CreateStartAnimationRequest(
      builder,
      _ledstrip_id,
      _o.Frequency,
      _initial_frame_buffer);
  }
}

public class StartAnimationRequestT
{
  public string LedstripId { get; set; }
  public float Frequency { get; set; }
  public List<Borealis.Communication.Messages.FrameMessageT> InitialFrameBuffer { get; set; }

  public StartAnimationRequestT() {
    this.LedstripId = null;
    this.Frequency = 0.0f;
    this.InitialFrameBuffer = null;
  }
}

public struct PauseAnimationRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static PauseAnimationRequest GetRootAsPauseAnimationRequest(ByteBuffer _bb) { return GetRootAsPauseAnimationRequest(_bb, new PauseAnimationRequest()); }
  public static PauseAnimationRequest GetRootAsPauseAnimationRequest(ByteBuffer _bb, PauseAnimationRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PauseAnimationRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string LedstripId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLedstripIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetLedstripIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetLedstripIdArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Borealis.Communication.Messages.PauseAnimationRequest> CreatePauseAnimationRequest(FlatBufferBuilder builder,
      StringOffset ledstrip_idOffset = default(StringOffset)) {
    builder.StartTable(1);
    PauseAnimationRequest.AddLedstripId(builder, ledstrip_idOffset);
    return PauseAnimationRequest.EndPauseAnimationRequest(builder);
  }

  public static void StartPauseAnimationRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddLedstripId(FlatBufferBuilder builder, StringOffset ledstripIdOffset) { builder.AddOffset(0, ledstripIdOffset.Value, 0); }
  public static Offset<Borealis.Communication.Messages.PauseAnimationRequest> EndPauseAnimationRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.PauseAnimationRequest>(o);
  }
  public PauseAnimationRequestT UnPack() {
    var _o = new PauseAnimationRequestT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(PauseAnimationRequestT _o) {
    _o.LedstripId = this.LedstripId;
  }
  public static Offset<Borealis.Communication.Messages.PauseAnimationRequest> Pack(FlatBufferBuilder builder, PauseAnimationRequestT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.PauseAnimationRequest>);
    var _ledstrip_id = _o.LedstripId == null ? default(StringOffset) : builder.CreateString(_o.LedstripId);
    return CreatePauseAnimationRequest(
      builder,
      _ledstrip_id);
  }
}

public class PauseAnimationRequestT
{
  public string LedstripId { get; set; }

  public PauseAnimationRequestT() {
    this.LedstripId = null;
  }
}

public struct StopAnimationRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static StopAnimationRequest GetRootAsStopAnimationRequest(ByteBuffer _bb) { return GetRootAsStopAnimationRequest(_bb, new StopAnimationRequest()); }
  public static StopAnimationRequest GetRootAsStopAnimationRequest(ByteBuffer _bb, StopAnimationRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StopAnimationRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string LedstripId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLedstripIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetLedstripIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetLedstripIdArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Borealis.Communication.Messages.StopAnimationRequest> CreateStopAnimationRequest(FlatBufferBuilder builder,
      StringOffset ledstrip_idOffset = default(StringOffset)) {
    builder.StartTable(1);
    StopAnimationRequest.AddLedstripId(builder, ledstrip_idOffset);
    return StopAnimationRequest.EndStopAnimationRequest(builder);
  }

  public static void StartStopAnimationRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddLedstripId(FlatBufferBuilder builder, StringOffset ledstripIdOffset) { builder.AddOffset(0, ledstripIdOffset.Value, 0); }
  public static Offset<Borealis.Communication.Messages.StopAnimationRequest> EndStopAnimationRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.StopAnimationRequest>(o);
  }
  public StopAnimationRequestT UnPack() {
    var _o = new StopAnimationRequestT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(StopAnimationRequestT _o) {
    _o.LedstripId = this.LedstripId;
  }
  public static Offset<Borealis.Communication.Messages.StopAnimationRequest> Pack(FlatBufferBuilder builder, StopAnimationRequestT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.StopAnimationRequest>);
    var _ledstrip_id = _o.LedstripId == null ? default(StringOffset) : builder.CreateString(_o.LedstripId);
    return CreateStopAnimationRequest(
      builder,
      _ledstrip_id);
  }
}

public class StopAnimationRequestT
{
  public string LedstripId { get; set; }

  public StopAnimationRequestT() {
    this.LedstripId = null;
  }
}

public struct AnimationBufferRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static AnimationBufferRequest GetRootAsAnimationBufferRequest(ByteBuffer _bb) { return GetRootAsAnimationBufferRequest(_bb, new AnimationBufferRequest()); }
  public static AnimationBufferRequest GetRootAsAnimationBufferRequest(ByteBuffer _bb, AnimationBufferRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AnimationBufferRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string LedstripId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLedstripIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetLedstripIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetLedstripIdArray() { return __p.__vector_as_array<byte>(4); }
  public ushort FrameCount { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<Borealis.Communication.Messages.AnimationBufferRequest> CreateAnimationBufferRequest(FlatBufferBuilder builder,
      StringOffset ledstrip_idOffset = default(StringOffset),
      ushort frame_count = 0) {
    builder.StartTable(2);
    AnimationBufferRequest.AddLedstripId(builder, ledstrip_idOffset);
    AnimationBufferRequest.AddFrameCount(builder, frame_count);
    return AnimationBufferRequest.EndAnimationBufferRequest(builder);
  }

  public static void StartAnimationBufferRequest(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddLedstripId(FlatBufferBuilder builder, StringOffset ledstripIdOffset) { builder.AddOffset(0, ledstripIdOffset.Value, 0); }
  public static void AddFrameCount(FlatBufferBuilder builder, ushort frameCount) { builder.AddUshort(1, frameCount, 0); }
  public static Offset<Borealis.Communication.Messages.AnimationBufferRequest> EndAnimationBufferRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.AnimationBufferRequest>(o);
  }
  public AnimationBufferRequestT UnPack() {
    var _o = new AnimationBufferRequestT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(AnimationBufferRequestT _o) {
    _o.LedstripId = this.LedstripId;
    _o.FrameCount = this.FrameCount;
  }
  public static Offset<Borealis.Communication.Messages.AnimationBufferRequest> Pack(FlatBufferBuilder builder, AnimationBufferRequestT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.AnimationBufferRequest>);
    var _ledstrip_id = _o.LedstripId == null ? default(StringOffset) : builder.CreateString(_o.LedstripId);
    return CreateAnimationBufferRequest(
      builder,
      _ledstrip_id,
      _o.FrameCount);
  }
}

public class AnimationBufferRequestT
{
  public string LedstripId { get; set; }
  public ushort FrameCount { get; set; }

  public AnimationBufferRequestT() {
    this.LedstripId = null;
    this.FrameCount = 0;
  }
}

public struct AnimationBufferReply : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static AnimationBufferReply GetRootAsAnimationBufferReply(ByteBuffer _bb) { return GetRootAsAnimationBufferReply(_bb, new AnimationBufferReply()); }
  public static AnimationBufferReply GetRootAsAnimationBufferReply(ByteBuffer _bb, AnimationBufferReply obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AnimationBufferReply __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Borealis.Communication.Messages.FrameMessage? FrameBuffer(int j) { int o = __p.__offset(4); return o != 0 ? (Borealis.Communication.Messages.FrameMessage?)(new Borealis.Communication.Messages.FrameMessage()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int FrameBufferLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Borealis.Communication.Messages.AnimationBufferReply> CreateAnimationBufferReply(FlatBufferBuilder builder,
      VectorOffset frame_bufferOffset = default(VectorOffset)) {
    builder.StartTable(1);
    AnimationBufferReply.AddFrameBuffer(builder, frame_bufferOffset);
    return AnimationBufferReply.EndAnimationBufferReply(builder);
  }

  public static void StartAnimationBufferReply(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddFrameBuffer(FlatBufferBuilder builder, VectorOffset frameBufferOffset) { builder.AddOffset(0, frameBufferOffset.Value, 0); }
  public static VectorOffset CreateFrameBufferVector(FlatBufferBuilder builder, Offset<Borealis.Communication.Messages.FrameMessage>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateFrameBufferVectorBlock(FlatBufferBuilder builder, Offset<Borealis.Communication.Messages.FrameMessage>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFrameBufferVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Borealis.Communication.Messages.FrameMessage>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFrameBufferVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Borealis.Communication.Messages.FrameMessage>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartFrameBufferVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Borealis.Communication.Messages.AnimationBufferReply> EndAnimationBufferReply(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.AnimationBufferReply>(o);
  }
  public AnimationBufferReplyT UnPack() {
    var _o = new AnimationBufferReplyT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(AnimationBufferReplyT _o) {
    _o.FrameBuffer = new List<Borealis.Communication.Messages.FrameMessageT>();
    for (var _j = 0; _j < this.FrameBufferLength; ++_j) {_o.FrameBuffer.Add(this.FrameBuffer(_j).HasValue ? this.FrameBuffer(_j).Value.UnPack() : null);}
  }
  public static Offset<Borealis.Communication.Messages.AnimationBufferReply> Pack(FlatBufferBuilder builder, AnimationBufferReplyT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.AnimationBufferReply>);
    var _frame_buffer = default(VectorOffset);
    if (_o.FrameBuffer != null) {
      var __frame_buffer = new Offset<Borealis.Communication.Messages.FrameMessage>[_o.FrameBuffer.Count];
      for (var _j = 0; _j < __frame_buffer.Length; ++_j) { __frame_buffer[_j] = Borealis.Communication.Messages.FrameMessage.Pack(builder, _o.FrameBuffer[_j]); }
      _frame_buffer = CreateFrameBufferVector(builder, __frame_buffer);
    }
    return CreateAnimationBufferReply(
      builder,
      _frame_buffer);
  }
}

public class AnimationBufferReplyT
{
  public List<Borealis.Communication.Messages.FrameMessageT> FrameBuffer { get; set; }

  public AnimationBufferReplyT() {
    this.FrameBuffer = null;
  }
}

public struct SetLedstripColorRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static SetLedstripColorRequest GetRootAsSetLedstripColorRequest(ByteBuffer _bb) { return GetRootAsSetLedstripColorRequest(_bb, new SetLedstripColorRequest()); }
  public static SetLedstripColorRequest GetRootAsSetLedstripColorRequest(ByteBuffer _bb, SetLedstripColorRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SetLedstripColorRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string LedstripId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLedstripIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetLedstripIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetLedstripIdArray() { return __p.__vector_as_array<byte>(4); }
  public Borealis.Communication.Messages.FrameMessage? Frame { get { int o = __p.__offset(6); return o != 0 ? (Borealis.Communication.Messages.FrameMessage?)(new Borealis.Communication.Messages.FrameMessage()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<Borealis.Communication.Messages.SetLedstripColorRequest> CreateSetLedstripColorRequest(FlatBufferBuilder builder,
      StringOffset ledstrip_idOffset = default(StringOffset),
      Offset<Borealis.Communication.Messages.FrameMessage> frameOffset = default(Offset<Borealis.Communication.Messages.FrameMessage>)) {
    builder.StartTable(2);
    SetLedstripColorRequest.AddFrame(builder, frameOffset);
    SetLedstripColorRequest.AddLedstripId(builder, ledstrip_idOffset);
    return SetLedstripColorRequest.EndSetLedstripColorRequest(builder);
  }

  public static void StartSetLedstripColorRequest(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddLedstripId(FlatBufferBuilder builder, StringOffset ledstripIdOffset) { builder.AddOffset(0, ledstripIdOffset.Value, 0); }
  public static void AddFrame(FlatBufferBuilder builder, Offset<Borealis.Communication.Messages.FrameMessage> frameOffset) { builder.AddOffset(1, frameOffset.Value, 0); }
  public static Offset<Borealis.Communication.Messages.SetLedstripColorRequest> EndSetLedstripColorRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.SetLedstripColorRequest>(o);
  }
  public SetLedstripColorRequestT UnPack() {
    var _o = new SetLedstripColorRequestT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SetLedstripColorRequestT _o) {
    _o.LedstripId = this.LedstripId;
    _o.Frame = this.Frame.HasValue ? this.Frame.Value.UnPack() : null;
  }
  public static Offset<Borealis.Communication.Messages.SetLedstripColorRequest> Pack(FlatBufferBuilder builder, SetLedstripColorRequestT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.SetLedstripColorRequest>);
    var _ledstrip_id = _o.LedstripId == null ? default(StringOffset) : builder.CreateString(_o.LedstripId);
    var _frame = _o.Frame == null ? default(Offset<Borealis.Communication.Messages.FrameMessage>) : Borealis.Communication.Messages.FrameMessage.Pack(builder, _o.Frame);
    return CreateSetLedstripColorRequest(
      builder,
      _ledstrip_id,
      _frame);
  }
}

public class SetLedstripColorRequestT
{
  public string LedstripId { get; set; }
  public Borealis.Communication.Messages.FrameMessageT Frame { get; set; }

  public SetLedstripColorRequestT() {
    this.LedstripId = null;
    this.Frame = null;
  }
}

public struct ClearLedstripRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static ClearLedstripRequest GetRootAsClearLedstripRequest(ByteBuffer _bb) { return GetRootAsClearLedstripRequest(_bb, new ClearLedstripRequest()); }
  public static ClearLedstripRequest GetRootAsClearLedstripRequest(ByteBuffer _bb, ClearLedstripRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClearLedstripRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string LedstripId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLedstripIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetLedstripIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetLedstripIdArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Borealis.Communication.Messages.ClearLedstripRequest> CreateClearLedstripRequest(FlatBufferBuilder builder,
      StringOffset ledstrip_idOffset = default(StringOffset)) {
    builder.StartTable(1);
    ClearLedstripRequest.AddLedstripId(builder, ledstrip_idOffset);
    return ClearLedstripRequest.EndClearLedstripRequest(builder);
  }

  public static void StartClearLedstripRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddLedstripId(FlatBufferBuilder builder, StringOffset ledstripIdOffset) { builder.AddOffset(0, ledstripIdOffset.Value, 0); }
  public static Offset<Borealis.Communication.Messages.ClearLedstripRequest> EndClearLedstripRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.ClearLedstripRequest>(o);
  }
  public ClearLedstripRequestT UnPack() {
    var _o = new ClearLedstripRequestT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClearLedstripRequestT _o) {
    _o.LedstripId = this.LedstripId;
  }
  public static Offset<Borealis.Communication.Messages.ClearLedstripRequest> Pack(FlatBufferBuilder builder, ClearLedstripRequestT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.ClearLedstripRequest>);
    var _ledstrip_id = _o.LedstripId == null ? default(StringOffset) : builder.CreateString(_o.LedstripId);
    return CreateClearLedstripRequest(
      builder,
      _ledstrip_id);
  }
}

public class ClearLedstripRequestT
{
  public string LedstripId { get; set; }

  public ClearLedstripRequestT() {
    this.LedstripId = null;
  }
}

public struct GetDriverStatusRequest : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static GetDriverStatusRequest GetRootAsGetDriverStatusRequest(ByteBuffer _bb) { return GetRootAsGetDriverStatusRequest(_bb, new GetDriverStatusRequest()); }
  public static GetDriverStatusRequest GetRootAsGetDriverStatusRequest(ByteBuffer _bb, GetDriverStatusRequest obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetDriverStatusRequest __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string LedstripId { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetLedstripIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetLedstripIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetLedstripIdArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Borealis.Communication.Messages.GetDriverStatusRequest> CreateGetDriverStatusRequest(FlatBufferBuilder builder,
      StringOffset ledstrip_idOffset = default(StringOffset)) {
    builder.StartTable(1);
    GetDriverStatusRequest.AddLedstripId(builder, ledstrip_idOffset);
    return GetDriverStatusRequest.EndGetDriverStatusRequest(builder);
  }

  public static void StartGetDriverStatusRequest(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddLedstripId(FlatBufferBuilder builder, StringOffset ledstripIdOffset) { builder.AddOffset(0, ledstripIdOffset.Value, 0); }
  public static Offset<Borealis.Communication.Messages.GetDriverStatusRequest> EndGetDriverStatusRequest(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.GetDriverStatusRequest>(o);
  }
  public GetDriverStatusRequestT UnPack() {
    var _o = new GetDriverStatusRequestT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(GetDriverStatusRequestT _o) {
    _o.LedstripId = this.LedstripId;
  }
  public static Offset<Borealis.Communication.Messages.GetDriverStatusRequest> Pack(FlatBufferBuilder builder, GetDriverStatusRequestT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.GetDriverStatusRequest>);
    var _ledstrip_id = _o.LedstripId == null ? default(StringOffset) : builder.CreateString(_o.LedstripId);
    return CreateGetDriverStatusRequest(
      builder,
      _ledstrip_id);
  }
}

public class GetDriverStatusRequestT
{
  public string LedstripId { get; set; }

  public GetDriverStatusRequestT() {
    this.LedstripId = null;
  }
}

public struct GetDriverStatusReply : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static GetDriverStatusReply GetRootAsGetDriverStatusReply(ByteBuffer _bb) { return GetRootAsGetDriverStatusReply(_bb, new GetDriverStatusReply()); }
  public static GetDriverStatusReply GetRootAsGetDriverStatusReply(ByteBuffer _bb, GetDriverStatusReply obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public GetDriverStatusReply __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Borealis.Communication.Messages.LedstripStatusMessage? LedstripStatuses(int j) { int o = __p.__offset(4); return o != 0 ? (Borealis.Communication.Messages.LedstripStatusMessage?)(new Borealis.Communication.Messages.LedstripStatusMessage()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int LedstripStatusesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Borealis.Communication.Messages.GetDriverStatusReply> CreateGetDriverStatusReply(FlatBufferBuilder builder,
      VectorOffset ledstrip_statusesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    GetDriverStatusReply.AddLedstripStatuses(builder, ledstrip_statusesOffset);
    return GetDriverStatusReply.EndGetDriverStatusReply(builder);
  }

  public static void StartGetDriverStatusReply(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddLedstripStatuses(FlatBufferBuilder builder, VectorOffset ledstripStatusesOffset) { builder.AddOffset(0, ledstripStatusesOffset.Value, 0); }
  public static VectorOffset CreateLedstripStatusesVector(FlatBufferBuilder builder, Offset<Borealis.Communication.Messages.LedstripStatusMessage>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateLedstripStatusesVectorBlock(FlatBufferBuilder builder, Offset<Borealis.Communication.Messages.LedstripStatusMessage>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLedstripStatusesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Borealis.Communication.Messages.LedstripStatusMessage>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateLedstripStatusesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Borealis.Communication.Messages.LedstripStatusMessage>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartLedstripStatusesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Borealis.Communication.Messages.GetDriverStatusReply> EndGetDriverStatusReply(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.GetDriverStatusReply>(o);
  }
  public GetDriverStatusReplyT UnPack() {
    var _o = new GetDriverStatusReplyT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(GetDriverStatusReplyT _o) {
    _o.LedstripStatuses = new List<Borealis.Communication.Messages.LedstripStatusMessageT>();
    for (var _j = 0; _j < this.LedstripStatusesLength; ++_j) {_o.LedstripStatuses.Add(this.LedstripStatuses(_j).HasValue ? this.LedstripStatuses(_j).Value.UnPack() : null);}
  }
  public static Offset<Borealis.Communication.Messages.GetDriverStatusReply> Pack(FlatBufferBuilder builder, GetDriverStatusReplyT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.GetDriverStatusReply>);
    var _ledstrip_statuses = default(VectorOffset);
    if (_o.LedstripStatuses != null) {
      var __ledstrip_statuses = new Offset<Borealis.Communication.Messages.LedstripStatusMessage>[_o.LedstripStatuses.Count];
      for (var _j = 0; _j < __ledstrip_statuses.Length; ++_j) { __ledstrip_statuses[_j] = Borealis.Communication.Messages.LedstripStatusMessage.Pack(builder, _o.LedstripStatuses[_j]); }
      _ledstrip_statuses = CreateLedstripStatusesVector(builder, __ledstrip_statuses);
    }
    return CreateGetDriverStatusReply(
      builder,
      _ledstrip_statuses);
  }
}

public class GetDriverStatusReplyT
{
  public List<Borealis.Communication.Messages.LedstripStatusMessageT> LedstripStatuses { get; set; }

  public GetDriverStatusReplyT() {
    this.LedstripStatuses = null;
  }
}

public struct ErrorReply : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static ErrorReply GetRootAsErrorReply(ByteBuffer _bb) { return GetRootAsErrorReply(_bb, new ErrorReply()); }
  public static ErrorReply GetRootAsErrorReply(ByteBuffer _bb, ErrorReply obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ErrorReply __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Borealis.Communication.Messages.ErrorIds ErrorId { get { int o = __p.__offset(4); return o != 0 ? (Borealis.Communication.Messages.ErrorIds)__p.bb.GetShort(o + __p.bb_pos) : Borealis.Communication.Messages.ErrorIds.UNKNOWNERROR; } }
  public string Message { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<Borealis.Communication.Messages.ErrorReply> CreateErrorReply(FlatBufferBuilder builder,
      Borealis.Communication.Messages.ErrorIds error_id = Borealis.Communication.Messages.ErrorIds.UNKNOWNERROR,
      StringOffset messageOffset = default(StringOffset)) {
    builder.StartTable(2);
    ErrorReply.AddMessage(builder, messageOffset);
    ErrorReply.AddErrorId(builder, error_id);
    return ErrorReply.EndErrorReply(builder);
  }

  public static void StartErrorReply(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddErrorId(FlatBufferBuilder builder, Borealis.Communication.Messages.ErrorIds errorId) { builder.AddShort(0, (short)errorId, 0); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(1, messageOffset.Value, 0); }
  public static Offset<Borealis.Communication.Messages.ErrorReply> EndErrorReply(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.ErrorReply>(o);
  }
  public ErrorReplyT UnPack() {
    var _o = new ErrorReplyT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ErrorReplyT _o) {
    _o.ErrorId = this.ErrorId;
    _o.Message = this.Message;
  }
  public static Offset<Borealis.Communication.Messages.ErrorReply> Pack(FlatBufferBuilder builder, ErrorReplyT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.ErrorReply>);
    var _message = _o.Message == null ? default(StringOffset) : builder.CreateString(_o.Message);
    return CreateErrorReply(
      builder,
      _o.ErrorId,
      _message);
  }
}

public class ErrorReplyT
{
  public Borealis.Communication.Messages.ErrorIds ErrorId { get; set; }
  public string Message { get; set; }

  public ErrorReplyT() {
    this.ErrorId = Borealis.Communication.Messages.ErrorIds.UNKNOWNERROR;
    this.Message = null;
  }
}

public struct SuccessReply : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static SuccessReply GetRootAsSuccessReply(ByteBuffer _bb) { return GetRootAsSuccessReply(_bb, new SuccessReply()); }
  public static SuccessReply GetRootAsSuccessReply(ByteBuffer _bb, SuccessReply obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SuccessReply __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartSuccessReply(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<Borealis.Communication.Messages.SuccessReply> EndSuccessReply(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Borealis.Communication.Messages.SuccessReply>(o);
  }
  public SuccessReplyT UnPack() {
    var _o = new SuccessReplyT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(SuccessReplyT _o) {
  }
  public static Offset<Borealis.Communication.Messages.SuccessReply> Pack(FlatBufferBuilder builder, SuccessReplyT _o) {
    if (_o == null) return default(Offset<Borealis.Communication.Messages.SuccessReply>);
    StartSuccessReply(builder);
    return EndSuccessReply(builder);
  }
}

public class SuccessReplyT
{

  public SuccessReplyT() {
  }
}


}
